### ISSUE TITLE
Pro zoom level

### ISSUE THREAD

**Issue by EmileSpecs** [briis/unifiprotect#162]
Would it be possible to add a service to set the zoom (optical) level of the Pro cameras (G3/G4 Pro)?

**Comment by briis** [comment]
I will look in to that.

**Comment by briis** [comment]
Hi @EmileSpecs 
I believe I have now implemented this. It will be out with the next release, which currently has no date, but I would appreciate if you could test it for me. In order to do that, please ensure you have upgraded to 0.7.0 first, and then copy the following files from this Repo in to your `custom_components/unifiprotect` directory:

````
camera.py
const.py
manifest.json
services.yaml
````

Restart Home assistant, and you should now have a new service called `unifiprotect.set_zoom_position` where you can set the zoom position between 0 and 100, where 0 is No Zoom and 100 is Max Zoom.

**Comment by EmileSpecs** [comment]
Hi @briis 
Thanks for the quick addition!

Yes, it works!

Had to dig a little to get the name of the property to set (position), but once I figured that out it worked.

Thanks again!

**Comment by briis** [comment]
Normally when a new service shows up, go to developer tools, select the service and do a hard refresh of the browser - that will give the help text. (These are cached by HA)
Anyway, glad it works. I am working on a few other things, so this will not be officially released right now, but you can just keep the files in your directory, and you will not have issues when a new update comes out.

**Comment by briis** [comment]
Released in 7.1, so closing this issue now.
