### ISSUE TITLE
Delay of stream

### ISSUE THREAD

**Issue by cazar86** [briis/unifiprotect#169]
I am running home assistant on an unraid server using docker. When displaying the cameras live streams on a lovelace dashboard there is about a 20 second delay. I'm pretty new to all of this so was wondering if I'm doing something wrong or if it's an issue with how it works on an unraid docker container. Nice addon, btw.

**Comment by briis** [comment]
Hi,
This is a known issue, but cannot be fixed by this integration. We supply a link to a RTSP stream to Home Assistant, and then the `stream` component in HA, does all the rendering. I have reports for delay from 5-20 sec. and unfortunately there is nothing I can do about it.
If you do not have `stream:` in your `configuration.yaml`, add that and you might see a slight improvement, but the delay will still be there.
