### ISSUE TITLE
Feature request: MFA support?

### ISSUE THREAD

**Issue by ppenders** [briis/unifiprotect#180]
Hi!

I've enabled MFA due to security reasons as apparently UI suffered some sort of security breach. Of course now the integration broke. Any chance you could add support for MFA (probably highly unlikely) or another strong authentication method?

Thx,

Perry

**Comment by briis** [comment]
I know and this is always good to do.
The issue is not with this Integration, as we do not use Ubiquiti SSO, we are only working on the local LAN. If you remember when you set it up, you created a Local account in Unifi Protect - When you afterwards enable 2FA, then UI resets the permissions on all local accounts.
So the fix is, go in to the Protect Web App. Find the user you are using for HA, and give them back the Admin Permissions. Then restart Home Assistant.
I wrote a post on it here also https://community.home-assistant.io/t/custom-component-unifi-protect/158041/476?u=briis

**Comment by briis** [comment]
I believe this has been answered, so I will close the issue. If you disagree, please re-open.
