### ISSUE TITLE
Motion detection at certain times stops working

### ISSUE THREAD

**Issue by rafastanger** [briis/unifiprotect#197]
Hello, I have Unifi Protect version 1.17.3 running on a UCK2+ with firmware 2.0.27. Unifi Protect HA integration is at version 0.8.2.

Motion detection at certain times stops working. In the Unifi Protect interface (on UCK2+) it is possible to see that the cameras are detecting the movement and the time in which it happened is informed. In lovelace I have a card created with the camera entity with the Last Tripped Time attribute that is not updated. This happens for the 4 cameras I have, 3 Dome G3 and 1 Bullet G3.

Example. Looking now at Unif Protect, all my cameras have the last movement today and at Lovelace the information is from two days ago. I have an automation to turn on some lights based on the movement of the cameras and the time of day and they stop working.

When I reload Protect integration via the Home Assistant settings / integration menu, the information in Lovelace is updated and the automations are back.

**Comment by briis** [comment]
Are there any other errors or warnings in the Log file?

**Comment by remcoaalbregt** [comment]
I'm having the same issue, motion detection works perfectly in Unifi protect dashboard. But in Home assistant the motion state changes stop functioning after a few hours. Reloading the integration seems the resolve the issue for a short while, but just for about 3-4 hours.

I'm seeing a few related log entries at the time the motion events stop registering: 

```
Logger: homeassistant
Source: custom_components/unifiprotect/data.py:48
First occurred: 4:53:26 AM (4 occurrences)
Last logged: 5:59:01 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 120, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 297, in _get_device_list
    response = await self.req.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:83
Integration: Stream (documentation, issues)
First occurred: 5:52:36 AM (4 occurrences)
Last logged: 6:41:19 AM

Error opening stream rtsp://192.168.1.1:7447/xxxxxxxxxxxxx
```

```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:251
Integration: Stream (documentation, issues)
First occurred: 4:53:14 AM (7 occurrences)
Last logged: 7:07:15 AM

Error demuxing stream:
Error demuxing stream: [Errno 1] Operation not permitted: 'rtsp://192.168.1.1:7447/xxxxxxxxxxxxx'
```

There are some timeout/lost connection messages to other unrelated devices. It looks like the motion sensor is unable to report any changes after the connection to the camera was lost.

**Comment by rafastanger** [comment]
Logger: custom_components.unifiprotect.data
Source: custom_components/unifiprotect/data.py:48
Integration: Unifi Protect (documentation, issues)
First occurred: 21:47:46 (1 occurrences)
Last logged: 21:47:46

Error while updating
Traceback (most recent call last):
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 120, in update
    await self._get_device_list(not self.ws_connection)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 294, in _get_device_list
    await self.ensure_authenticated()
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 190, in ensure_authenticated
    await self.authenticate()
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 207, in authenticate
    response = await self.request("post", url=url, json=auth)
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 990, in request
    raise NvrError(f"Error requesting data from {self._host}: {err}") from None
pyunifiprotect.unifi_protect_server.NvrError: Error requesting data from 192.168.1.199: Cannot connect to host 192.168.1.199:443 ssl:False [Connect call failed ('192.168.1.199', 443)]

**Comment by briis** [comment]
Just to ensure where the error lies: Could you check the Activity Log in UniFi Protect, and see if there are any messages for the same time frame. I get this occasionally, when the Camera disconnects from my UDMP, for whatever reason.

**Comment by remcoaalbregt** [comment]
No related activity logs around that time. Camera never disconnected since last UDM restart. I just disconnected the camera by removing the cable, that only triggered errors on the stream component.

I'm not entirely sure the issues of @rafastanger and me are the same. I don't want to hijack his issue, please do tell if I should open my own ;-)

**Comment by rafastanger** [comment]
> Just to ensure where the error lies: Could you check the Activity Log in UniFi Protect, and see if there are any messages for the same time frame. I get this occasionally, when the Camera disconnects from my UDMP, for whatever reason.

I will wait for a new stop and collect and analyze the logs more consistently in all the environment (VM of HA, networking, HA, Protect, etc.).

**Comment by houshasen** [comment]
I believe my situation is the same.

I currently have two Home Assistant instances:
1. Home Assistant OS on ProxMox Virtual Environment using Intel NUC
2. Home Assistant OS on Rasberry Pi 3B

I have it setup so Doorbell is exposed to Homekit so HomePod ring gets triggered, and also Sonos speakers have TTS. Both worked fine during original setup.

After several hours of running on the setup 1 (newer addition), this morning I noticed my Unifi Doorbell event stopped working on setup 1. After rebooting the HassOS instance on the NUC, it started to work again. I then checked setup 2, and it correctly register all doorbell push events (except I guess my setup have 3 hours time offset). 

Camera Stream works fine i.e. Doorbell still remains to be on Home Assistant OS on NUC, just doorbell ring not working, but I surmise similar to this post, motion probably is to working either (I just haven't tested). UniFi official Protect App still triggered doorbell ring so Doorbell to Protect controller still seemed to be working.

Because rebooting HA OS fixed, I believe it has to be something between Protect Controller to HA OS. As far as IP address of Camera, it has not changed over past couple weeks so that does not seem to be an issue.

Interesting part (to me) is that this similar issue exist on Homebridge UniFi Protect Plugin. I had one running on Docker and the other on standalone Rasberry Pi. The latter worked consistently and former sporadically, and Homebridge developer said, it is known issue and to be fixed in the future.

**Comment by bdraco** [comment]
> Interesting part (to me) is that this similar issue exist on Homebridge UniFi Protect Plugin. I had one running on Docker and the other on standalone Rasberry Pi. The latter worked consistently and former sporadically, and Homebridge developer said, it is known issue and to be fixed in the future.

Do you have a link to where the known issue is described?

**Comment by houshasen** [comment]
> > Interesting part (to me) is that this similar issue exist on Homebridge UniFi Protect Plugin. I had one running on Docker and the other on standalone Rasberry Pi. The latter worked consistently and former sporadically, and Homebridge developer said, it is known issue and to be fixed in the future.
> 
> Do you have a link to where the known issue is described?

Yes. This is the link: https://github.com/hjdhjd/homebridge-unifi-protect/issues/286#issuecomment-776032418

**Comment by JohnGalt1717** [comment]
I'm getting this with the latest update. It worked for 6+ months without fail and now it doesn't.

**Comment by briis** [comment]
You need to supply more information. Nothing has changed in this Integration recently, and the changes in HA should have no effect.

**Comment by JohnGalt1717** [comment]
It now started working again. Must have been a UniFi firmware issue.

**Comment by briis** [comment]
As this is an old thread, and no new information is comming in, I will close this issue. Please open a new issue, if this happens again.
