### ISSUE TITLE
Does not work with UnifiOS

### ISSUE THREAD

**Issue by robertomano24** [briis/unifiprotect#21]
Hello, 

I did not expect that it would (especially considering the UDMP is still early access), but I thought I would pass along anyway that this integration is not working with UnifiOS on the Unifi Dream Machine Pro (fw 1.6.4). Now that UnifiOS is adding the controllers into containers in a way they never have, I assume this is simply a weird auth/connection issue or something. 

Here is the error:
`2020-01-29 07:58:34 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform unifiprotect.camera: Unable to set up component.`

Here is my config:
```
unifiprotect:
  host: 10.0.0.1
  username: !secret unifi_local_un
  password: !secret unifi_local_pw
```
I have added a local user and followed the steps in the README (e.g., enabling the RTSP streams, etc). 

If it is something you would like to work on to resolve, I would be more than glad to test things for you and offer assistant however possible as time progresses.

**Comment by briis** [comment]
Hi Robert,
Thanks for the feedback. I must admit when you wrote this, I did not know what UnifiOS was, but I did some digging, and found that UDMP Pro is currently only released in the US (I am based in Europe), and that this is the first device with UnifiOS.

The whole concept of UnifiOS is the Single Sign On, to all services, thus you are most likely right that the issue here lies with the Authentication. As with Unifi Protect, Ubiquiti is not very good in documenting the API, and I found nothing about how Authentication works for UnifiOS. Might come later, but with the history of Ubiquiti, I doubt it.

So thank you for your offer to help and test, but I have honestly no clue on where to start, and without having access to a device, it will be almost impossible to modify this to work with UnifiOS for the time being. I can only reach out to the community, to see if someone, with access to a device running UnifiOS, can modify the code to work with this.

If and when, I can get access to a device, I will most certainly try to get the code to work, but for now I cannot help. Sorry.

**Comment by Silvenga** [comment]
I do have a UDMP to test with, so I was able to make a proxy that modifies the requests from unifiprotect, to work with the new SSO system (and the unified protect/unifi API):

https://github.com/Silvenga/unifi-udm-api-proxy (it's docker based)

To run (the docker compose assumes the UDMP is at `192.168.0.1`):

```
docker-compose up -d
```

And to configure:

```yaml
host: localhost
port: 5000
username: !secret unifiprotect_user
password: !secret unifiprotect_pass
```
----

Everything seems to work. The JWT that used to be returned on the Authorization header, is now a cookie. And things like the accessKey no longer do anything (but thankfully, unifiprotect is using sessions).

While I could make a pr to this project for proper support (and learn python) I worry about reducing your ability to refactor/add new functionality @briis - so I opted to make this a separate component that can be independently supported by those with UDMP's.

The worst part of the new system, whenever a request is invalid, the server either times out or returns a generic 404 error (i.e. 404 if a token cookie is sent to the auth endpoint, timeout if the token cookie is invalid, etc.). This makes development without the UDMP error prone at best.

**Comment by briis** [comment]
This is great news for the folks with a UDMP. I agree with you, that for now let us keep this as a separate component to ensure continued development - but when UDMP's are more general available, let us scout for the possibility to integrate this somehow.

It is not completely clear to me, from your description above, how this actually works? You spin up the Docker Container, and all calls get directed through this, and do you then let that container talk to my component. Or how does this work?

**Comment by Silvenga** [comment]
That's exactly how the project works @briis.

```
HA -> unifiprotect -> unifi-udm-api-proxy -> UDMP.
```

Internally, the proxy rewrites requests e.g. `/api/events -> /proxy/protect/api` or `/api/auth -> /api/auth/login`, headers e.g. `Authorization: TOKEN -> Cookie: TOKEN`, and rewrites the JWT e.g. `TOKEN -> refreshed token`.

**Comment by briis** [comment]
Hi Mark,
Could you write up a description on how to do this, so that everybody who has a UDMP can figure out how to set it up?
From the above I assume the only file you have changed is `unifi_protect_server.py` ? If that is the case, I will let you know if I change anything in that file, so that you can update your code.

**Comment by Silvenga** [comment]
No changes are required in your code @briis. The proxy masquerades as the old protect server. It's purely a compatibility shim and tries to act as a full abstraction (I still need to fix some _leaks_).

But I'll add docs around setting it up. I should publish an image if people use it too.

**Comment by briis** [comment]
Ahh, now I get it :) but as you can see, I got confused, so I little write of the setup procedure would be great. 
Thanks, great work.

**Comment by robertomano24** [comment]
@Silvenga I tried using your docker-compose and returned this error:

```Build FAILED.

CSC : error CS2015: '/src/src/UdmApi.Proxy/._Program.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/._FallbackMiddleware.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/Services/._ProtectAccessKeyProxy.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/._ProxyMiddleware.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/Services/._ProtectLoginProxy.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/Helpers/._MiddlewareExtensions.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/._Startup.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/Services/._ProtectProxy.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/Helpers/._ProxyHelper.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/Sessions/._SsoSessionCache.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
CSC : error CS2015: '/src/src/UdmApi.Proxy/Services/._IServiceProxy.cs' is a binary file instead of a text file [/src/src/UdmApi.Proxy/UdmApi.Proxy.csproj]
    0 Warning(s)
    11 Error(s)

Time Elapsed 00:00:01.10
ERROR: Service 'unifi-udm-api-proxy' failed to build: The command '/bin/sh -c dotnet build "UdmApi.Proxy.csproj" -c Release -o /app/build' returned a non-zero code: 1
```

**Comment by Silvenga** [comment]
@robertomano24 looks like your editor is making `._*` files, and the compiler doesn't like it. I published a docker image, which might be easier: [silvenga/unifi-udm-api-proxy](https://hub.docker.com/repository/docker/silvenga/unifi-udm-api-proxy)

@briis and pushed an update to the README. 😹

**Comment by briis** [comment]
Thanks. I have updated the README.md with a link to the Github Repository for the Proxy.

**Comment by robertomano24** [comment]
Just got around to trying this finally @Silvenga 
That downloaded and installed with no issue on my Unraid device.

**Comment by zacs** [comment]
FYI @briis in case you want to integrate this natively, the Homebridge Protect project has a PR in to do it. Should be possible to crib the logic from that if desired :) 

https://github.com/hjdhjd/homebridge-unifi-protect2/pull/11

**Comment by briis** [comment]
Well spotted. @zacs. I will look in to this when I have the time.

**Comment by Veldkornet** [comment]
Just got my UDM Pro only to find out that this isn’t working ;)

So, just adding my voice to the thread :)

```
2020-02-20 19:32:56 ERROR (MainThread) [homeassistant.setup] Error during setup of component unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/unifiprotect/__init__.py", line 111, in setup
    host, port, username, password, use_ssl, minimum_score
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 44, in __init__
    self._api_auth_bearer_token = self._get_api_auth_bearer_token()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 74, in _get_api_auth_bearer_token
    raise NvrError("Request failed: %s" % response.status)
AttributeError: 'Response' object has no attribute 'status'

```

**Comment by zacs** [comment]
@Veldkornet did you use the proxy linked to earlier in this issue? https://github.com/Silvenga/unifi-udm-api-proxy

**Comment by Veldkornet** [comment]
Yeah, the proxy is no good for me. I have other things running on port 5000 and this plugin doesn’t let you set different ports, so it’s not working.

**Comment by Veldkornet** [comment]
I’m not sure if this helps at all, but [this](https://github.com/jonbloom/homebridge-unifi-protect2) plugin is working for HomeBridge

**Comment by Silvenga** [comment]
This plugin supports alternative port @Veldkornet. Just add a port properly to the yaml, it's just not documented.

**Comment by Veldkornet** [comment]
Well I already made the Docker container listen on port 5443 and in the plugin yaml I added the port after the IP address of the Docker host, and it still doesn’t work

**Comment by greetoz** [comment]
I am using this integration with the UDM proxy docker. But it makes my Home Assistant very slow after about 24-36 hours. I need to restart HA then. In the Log i see a lot of errors that it has not received a response within 2 seconds of the sensors this integration makes. Removing the unifiprotect integration and all is well.

I don't know if its the integration or the proxy, but for me atleast its not working.

**Comment by briis** [comment]
It might vey well be my Integration that slows it down. Ideally the state of the binary_sensor (Motion Detection) should be pushed from the server, and that would require a Async Callback, which my Python skills are not sufficient to do at the moment. If that could be done, the poll frequency could be reduced for all others. 
For now, I have made a version in the `dev` branch, that only pulls the sensor every 10 seconds, instead of 2. You could try and download `sensor.py` from the `dev` branch and replace the file in your HA installation with this, to see if that makes a difference.

**Comment by greetoz** [comment]
I'll try that and report back! Will take a few days as the slowdown takes 1-2 days to occur.

**Comment by Veldkornet** [comment]
> I am using this integration with the UDM proxy docker. But it makes my Home Assistant very slow after about 24-36 hours. I need to restart HA then. In the Log i see a lot of errors that it has not received a response within 2 seconds of the sensors this integration makes. Removing the unifiprotect integration and all is well.
> 
> 
> 
> I don't know if its the integration or the proxy, but for me atleast its not working.

Man, is that the cause. My HomeAssistant has been a piece of 💩 lately in terms of speed.

**Comment by greetoz** [comment]
> bout 24-36 hours. I need to restart HA then. In the Log i see a lot of errors that it has not received a response within 2 seconds of the sensors this integration makes. Re

Yup took me some time to figure out. Im testing the DEV version of this integration now. I'll report back on this thread if it comes back or if problems are resolved.

**Comment by Silvenga** [comment]
My two cents from the proxy side of things:

### What could be happening

When an invalid/expired token is sent to the new UDM SSO based API, the request will timeout. This will quickly break HA as http connections are pooled. For self-protection, the proxy will attempt to detect this state within a couple of seconds, and kill the connection (to prevent taking down the HA server). And, no, the API doesn't do something sane like return 401.

This state of invalid tokens occurs in two cases:
- When the UDM upgrades/restarts, all existing tokens are purged. In theory, any clients (e.g. unifiprotect should reauth) or the proxy should cache the user's password/username and attempt to automatically create a new session (since this is new behavior from the new API). I'm trying to not persist user credentials to the disk if I can, so that might be an opt-in feature.
- With the new API, a new token is created for every request (and last for an hour, IIRC). This differs from the old API where the first token would never expire. The proxy will attempt to automatically switch the old token given to clients (e.g. unifiprotect) with the latest token automatically (and automatically capture new tokens). In old versions of the proxy, these tokens would be stored in memory, so restarting the proxy would cause the timeouts (since the tokens expired). In new versions of the proxy, the sessions are stored, so the proxy can be restarted.

@greetoz and @Veldkornet do you know if your UDMP device restarted or updated? And what version of the proxy are you using (and are you using the add-on now)? I would be interested in getting logs from the proxy as well.

I would like to better handle this case, but I'm unsure why HA seems to die when services are slow.

### Asides

- I have noticed some extensions in HA not handling slow services well. I've always thought it was more of a HA issue, and not the extension, but don't really know enough to profile python. Timeouts in services causing HA to crash and burn is an example of that.
- I do run unifiprotect + the proxy - most of the performance problems seems to originate from the UDMP TBH. It's not the fastest API.

**Comment by 1activegeek** [comment]
Is there any way to enable a debug or logs to indicate what could be wrong if something is wrong? I currently have a UDM-P, got the shim running in HASS. It looks like that communication is working fine and the auth is going through fine to the UDM-P as it has a bunch of 200 messages in supervisor log view. I can't find any errors or issues listed anywhere, but I'm not getting cameras or sensors showing up. No errors in the HA logs. Any help is appreciated.

**Comment by briis** [comment]
Great that it works for you now. Should you need to enable logging, add the following to your configuration.yaml file:

```yaml
logger:
  default: error
  logs:
    custom_components.unifiprotect: debug
```

**Comment by Cadish** [comment]
Is there anyway we can use the UDMP without proxy? The unifi component has been updated lately, so @kane610 has been able to find a fix to include Unifi OS... Would be great if we could extend his solution into this component...
https://github.com/home-assistant/core/pull/33766

**Comment by briis** [comment]
Hi @Cadish 
Thanks for the pointer. I just has a quick browse of the code, and it looks interesting. I cannot promise I can do that with my Python skills, but I will have a look at it, and make some tests. If I can rewrite the base communication engine to mimic the Unifi Implementation, then it might be possible. I will work on it, and let you know if I get something to test. (I don't have a UDM PRO, so I need someone to test that part)

**Comment by 1activegeek** [comment]
>  I will work on it, and let you know if I get something to test. (I don't have a UDM PRO, so I need someone to test that part)

Happy to test out if something comes about. Just drop me a ping if you get something that looks like it's workable and I can surely take a stab at it.

**Comment by greetoz** [comment]
@briis The dev version of your integration does not seem to slow down my HA instance so thats good. 

@Silvenga Yes, i could have restarted the UDM-Pro, but it also happens without restarting the UDM.. 

@briis again. I use the protect integration on non critical stuff now, so i am happy to test for you.

**Comment by Kane610** [comment]
I think it's a good God idea to migrate the integration to use aiohttp for proper async io handling

**Comment by Veldkornet** [comment]
I don’t know if it’s maybe gotten worse since the latest Protect update or something, but my HomeAssistant became basically unusable. As a test, I removed it from my configuration.yml and everything was happy again. As soon as I enable it again, everything starts going to hell within a few hours.
For example, communication to my Hue bridge times out or doesn’t work and I can’t control the lights.

There’s nothing specific in the logs that I can see. In HomeAssistant or in the proxy docker container... everything just gets slower.

I’m using version 0.1.6.

Initially when I had installed the configuration a month or 2 back, everything was okay. So it’s not clear to me if it came with an update of UniFiOS / the plugin / HomeAssistant....

**Comment by briis** [comment]
@Kane610: I am self-taught on Python, so it might take a while. Anyone who wants to help with the migration to fully Async, please come forward.

@Veldkornet: There is nothing in the latest changes that should affect performance the way you see it, and I personally I don't have the same experience. So it is hard for me to say why this is happening to you.

**Comment by Kane610** [comment]
> @Kane610: I am self-taught on Python, so it might take a while. Anyone who wants to help with the migration to fully Async, please come forward.
 Hey! Me too :)

**Comment by Veldkornet** [comment]
FYI, since updating to HA 0.109, the following is spamming the logs, not sure if it’s related or just something to fix in general...

```
2020-04-29 19:39:32 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 210: verify=self._verify_ssl,
2020-04-29 19:39:35 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for unifiprotect doing I/O at custom_components/unifiprotect/unifi_protect_server.py, line 109: verify=self._verify_ssl,
```

**Comment by Veldkornet** [comment]
After updating to v0.2.0 for #36 , the camera entities are no longer showing on my dashboard (the snapshots). Also if I try to click on one to get the stream, the stream fails.

```
2020-05-04 07:55:49 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 490, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 507, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/unifiprotect/camera.py", line 160, in async_camera_image
    last_image = await self.upv_object.get_snapshot_image(self._camera_id)
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 266, in get_snapshot_image
    access_key = await self._get_api_access_key()
  File "/config/custom_components/unifiprotect/unifi_protect_server.py", line 99, in _get_api_access_key
    json_response = await response.json()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1021, in json
    await self.read()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 358, in read
    block = await self.readany()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 380, in readany
    await self._wait('readany')
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 296, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

**Comment by briis** [comment]
Unfortunately I have not been able to test this with the Proxy on UnifiOS. I can confirm that it runs without any issues on the CloudKey.
Hopefully @Silvenga has time to look in to this.

**Comment by Veldkornet** [comment]
@briis it’s time to [join](https://eu.store.ui.com/collections/routing-switching/products/udm-pro) us ;)

**Comment by briis** [comment]
I am happy to say that with Version 0.3.0 this is now implemented as a direct feature. Enjoy

**Comment by 1activegeek** [comment]
Just to validate - so we no longer need the Unifi bridge component running?! You sir are awesome!

**Comment by briis** [comment]
YES, this is correct. Just remember to change the IP Address in the `configuration.yaml` file to the address of your UDMP and specify the port (443).
And the credit goes to @msvinth - he did all the work.

**Comment by Veldkornet** [comment]
I can confirm that it’s working, at least the snapshots are which is 90% of my use. 

My video streams don’t work, but... not sure if it’s just my setup since I’m using Protect 1.14.10. Can someone else check?

**Comment by briis** [comment]
I know that they worked for @msvinth as it was part of our tests. But I am not sure what version he is running.

**Comment by 1activegeek** [comment]
I plan to make a bunch of changes on HASS on Thurs, so I'll check it out then. Thanks so much briis, this is truly an awesome integration!!

**Comment by Veldkornet** [comment]
I think the video feed is working, it’s a strange situation but it works. 

So if I have the camera card on the dashboard, snapshots are working. Then I open one of these cameras and the feed just “spins” with a black screen. Then I need to push the play button. Close the stream. Reopen the stream, then it reopens as already “playing” and the streaming works. 

It could be a HomeAssistant thing as apposed to the integration, since the feed is working. 

As an additional test, I rang my doorbell ;) So this streams my camera feed from the front door over AirPlay to the the AppleTV,  this is all working as expected. It’s been a long time since I’ve had the feed to my TV working, so it’s looking good.

**Comment by msvinth** [comment]
@Veldkornet Streams works fine for me. I am on Protect 1.14.9. 
They take a little while to load 5-10 seconds the first time. Did you try to check the Preload stream? Seems to work better that way. 
I also have the Nest doorbell and the streaming for that works with the same slowness/delay.

**Comment by Veldkornet** [comment]
In the past, my experience was (in relation to using it for my doorbell):
- Pre-load on: Stream has around 10 seconds delay, but is faster to load
- Pre-load off: Stream has around 5 second delay, but takes a tiny bit longer to load 

That was a while ago though, I haven’t tried on the more recent HA versions.

**Comment by adandl** [comment]
Streaming works for me fine, but I'm not sure that the motion-sensor would also work okay.
In my environment it stays always on "clear" and does not change to "motion" at all.
Streaming works (but a little strange as explained above by @Veldkornet)
Direct connected without the proxy - which is great - thank you @briis !!!

UnifiProtect 1.14.9 running on UDM Pro

**Comment by msvinth** [comment]
@adandl I just played around with code for motion event and the UDM Pro Protect motion event data is returned correctly.
@briis I think the motion detection is currently broken after the move to async. I believe the DataUpdateCoordinator created in __init__ async_setup is not fully working. 
As described in https://developers.home-assistant.io/docs/integration_fetching_data/ 
this code is missing in the binary sensor to let the DataUpdateCoordinator update the sensor:

```
    @property
    def should_poll(self):
        """No need to poll. Coordinator notifies entity of updates."""
        return False

    @property
    def available(self):
        """Return if entity is available."""
        return self.coordinator.last_update_success

    async def async_added_to_hass(self):
        """When entity is added to hass."""
        self.async_on_remove(
            self.coordinator.async_add_listener(self.async_write_ha_state)
        )
```

**Comment by briis** [comment]
Thanks @msvinth. You are right this has been forgotten. I will make the correction tomorrow morning and send out an update.

**Comment by briis** [comment]
It is strange, that motion detection actually works on the CloudKey, with the V0.3.0, but seems not to be working on UnifiOS. Anyway, I have changed `sensor.py` and `binary_sensor.py`. Could you go here: https://github.com/briis/unifiprotect/tree/V0.3.1/custom_components/unifiprotect and download these 2 files, and replace them in the unifiprotect directory and tell me if it works.
/B

**Comment by adandl** [comment]
I replaced as suggested and it works superb now!

Thank you!

**Comment by msvinth** [comment]
@briis I have discovered a small problem on UnifiOS where my changes do not handle that the authentication token expires. I will make a PR to fix it.

**Comment by briis** [comment]
@adandl Great that this fixes it.
@msvinth I will wait to release a new version, until you have made your change.

**Comment by Silvenga** [comment]
Awesome! Can also confirm it works with the UDMP. Thanks everyone involved.

**Comment by briis** [comment]
With the above comments, I will now close this Issue.

**Comment by crkochan** [comment]
Just a heads up, the UNVR4 from the early access program, running the latest beta UnifiOS firmware and controllers, does not return a x-csrf-token response header to client requests.

A warning about non-public hardware running non-public software, in a closed issue. I realize this comment may not have much value, and perhaps when this stuff hits general release, it'll be working more like the UDMP.

Just in case it isn't though, I figured I'd let you know there's a potential problem lurking down the road.

**Comment by briis** [comment]
Thanks the Heads-Up @crkochan. I appreciate this - As Ubiquiti is not very forthcoming in sharing the API and potential changes, the only thing we can do is adapt when it hits us.
