### ISSUE TITLE
binary_sensor keeps failing

### ISSUE THREAD

**Issue by schwickster** [briis/unifiprotect#236]
Hey,

Every now and then my connection with the G4 doorbell keeps losing connection because my UDM pro keeps resetting.
This results in the binary_sensor not updating (after regaining connection) when somebody pressed the doorbell. Restarting Home Assistant fixes the problem, but it´s annoying to keep doing so.

Using:
Home Assistant 2021.5.2
Unifi protect 1.18.1
Unifi network 6.2.25
UDM pro 1.9.3
Unifi Protect for Home Assistant 0.8.7

**Comment by briis** [comment]
I am sorry, I cannot replicate this. I can remove the power from a Camera, and then plug it in again, and after a little while I get the image and entities back. Yes, you will see a few errors in the Log file, but operations is fine without restarting HA or reloading the integration.

I have the same setup as you describe above. I would recommend that you get the underlying problem fixed, so that your UDMP does not reset all the time - mine never does.
