### ISSUE TITLE
Manage away mode / movement notifications from HA

### ISSUE THREAD

**Issue by embcla** [briis/unifiprotect#256]
Hi

I just found your HA addon and it looks great.
Have you investigated how to/if possible to set away mode in protect?
I currently have to do it manually when I leave (don't want to give my location to Ubiquiti), would be great to tie it to my HA automations!

Thanks for your work!

**Comment by briis** [comment]
There is not really an *Away Mode* in Unifi Protect, there is only the possibility to activate a recording mode (Smart, Motion or Always)  or not. But the beauty with Home Assistant, is that you can now start an automation, that triggers on *Last person Leaving the House* or *First person coming home* and then set the recording mode.

I have a few automations that work with that:
- When the last person leaves the house (Based on the device_tracker on the families phones), then all my camras are set to record on motion
- When the first person comes home, all cameras are set to not record (I don't want recording at all when anyone of the Family is home
- When my Front Door lock, is going to the locked state, all outdoor cameras are set to record
- When the Front door gets unlocked, I disable recording.

These are just a few examples on how I use it, and I think if you ask the community, there are several other great use cases.
You use the services described in README, to enable or disable recording in your automations.

Does this answer your question?

**Comment by embcla** [comment]
Hi

Yeah this is answers a lot of doubts I had.
So you don't use their notification system when cameras detect movement?
I found that would be useful for me, but I'd need a way to either set myself into away mode, or enable/disable those notifications when I leave/return.

Also all of this relates to that age-old issue of detecting presence reliably, but let's not go too much off topic 😆

**Comment by briis** [comment]
No I don't use what UI has to offer in the APP. When I started a long time ago with this, I found it unreliable (MIght have changed since then), and then I wanted something else to trigger if cameras are on or not.

As said, in my case I have a Lock on my Front Door, that is integrated in to Home Assistant. Whenever that door locks I arm the outside cameras. We might still be home, but gone to bed. And then the disarm when I unlock the door.

I also have an Alarm system integrated in to HA. Whenever that is set to Armed Away, I also arm the Indoor Cameras, and disarm them when the alarm is set to disarmed.

These two above, does not need any presence detection, thus I don't even need have my phone with me.

And yes, there are many situations where presence could be used to do the same, but as you said that is a long topic. Hope you can figure out a way that works for you.

**Comment by embcla** [comment]
Thank you, that closes it.
