### ISSUE TITLE
No doorbell text configuration available

### ISSUE THREAD

**Issue by incarvr6** [briis/unifiprotect#338]
### Home Assistant Version?

2021.11.3

### UniFi Protect Version

1.19.2

### UniFi Protect HA Integration version?

0.9.1

### What happened?

There is no option in configuration to preset doorbell text.
There is no way to access any original preconfigured texts with simbols 
![Screenshot_2021-11-14-12-41-26-96_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/49254419/141681487-d0a2b669-e6d9-413e-9d63-ab6ea98eb36d.jpg)

**Comment by AngellusMortis** [comment]
This is because the main docs on Github is ahead of the stable HACS version. The latest version is 0.10, but it is current marked as a beta because it requires Protect 1.20, which has not been released to GA yet. We are waiting for 1.20 to come out before we mark 0.10 stable. So it is an "upcoming feature". 

You can find the documentation that matches the 0.9.1 version at https://github.com/briis/unifiprotect/tree/release/0.9.x

**Comment by AngellusMortis** [comment]
Just as a heads up though, 0.10 does have breaking changes in it. So I apologize if you start using 0.9 now and 0.10 comes out within a week and you have to redo everything. 

The core binary/camera entities are not changed, but a lot of the other features are changed.

**Comment by incarvr6** [comment]
I been using integration for about year or so.
Well braking changes some times happens, but if it is for improving integration why not.

If only there would be a way to use talk back feature in HA it would be priceless. Original protect app sometimes is absolutely useless takes more than 10 seconds just to open it...

**Comment by AngellusMortis** [comment]
That is actually planned as well. I already have the feature for playing audio to cameras done in the underlaying library. We just have to implement a media player on top of it. Then you can play re-recorded MP3s and TTS to the camera. Two way live audio, will unfortunately require something a bit more (i.e. a frontend feature from core to allow voice chat).
