### ISSUE TITLE
Disk Health Sensors not numbered correctly

### ISSUE THREAD

**Issue by B-Hartley** [briis/unifiprotect#385]
### Home Assistant Version?

2021.12.0b3

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

0.11-beta.2

### What happened?

Disk Health sensors are not numbered corrrectly.
At the moment I have 2 discs failed that are awaiting replacement.
So I have:

HDD-1 - Empty
HDD-2 - OK
HDD-3 - Empty
HDD-4 - OK

However in this integration I see:

Disk 0 Health - OK
Disk 1 Health - OK

and no other sensors.

Let me know if I can provide any more info, help.

**Comment by AngellusMortis** [comment]
I know it is annoying, but unfortunately this is not a bug. It is "working as expected". UniFi Protect does not actually provide any information about where the disks are installed. Just how many there are, their model number, capacity and if they are failing or not.

UniFiOS provides the data about where they are installed, which is completely separate from UniFi Protect. You are seeing the HDD-1 / HDD-2 / HDD-3 / HDD-4 interface from your UniFiOS console, not from Protect. UniFiOS is a completely different API and WS I would have to use to be able to get that data.

I just installed a couple of random drives I had laying around in NVR to illustrate (still need to buy my real NVR disks): 

![image](https://user-images.githubusercontent.com/490848/145218313-3eafab77-3210-46d5-a0d7-561691d33050.png)

![image](https://user-images.githubusercontent.com/490848/145218373-f552e48f-02fb-4687-a688-637de0445213.png)

**Comment by B-Hartley** [comment]
Fair enough, thanks for the response.
It's fine of course, all I need to know is that a drive has failed.
I can then look on unifios to find out which one !

Out of interest, do you know if it gives them in order, so if I do have 4 drives in will they display in the right order, or is it random?
or haven't you experimented enough to know ?

**Comment by AngellusMortis** [comment]
> It's fine of course, all I need to know is that a drive has failed.

That is exactly my thought! I do not want to pull _everything_ from UniFi Protect into Home Assistant, just what is hopefully useful. You can still always jump over there to get the real details.

> do you know if it gives them in order

No idea. I would assume they are likely in the correct order though since Linux devices are very logically named / ordered / etc. It seems kind of silly for them not to just use them in the order they are given. The model numbers are exposed as attributes, but that likely will not help a lot because I assume most people will be using the same exact model for all of their bays. I already ordered 3 Skyhawks for my NVR to replace the old drives I have it in now.

![image](https://user-images.githubusercontent.com/490848/145230310-48b0b8b0-dc2e-4532-a4cd-40e1a2fa8072.png)
