### ISSUE TITLE
Allow to set doorbell LCD text dynamically

### ISSUE THREAD

**Issue by edwardmp** [briis/unifiprotect#396]
### New Feature

As described in #263, I want to be able to set the LCD text value dynamically, which is no longer in v0.11, while it was before.

**Comment by AngellusMortis** [comment]
We talked about this and decided to make a new service with the same purpose as the old one (set LCD text), but it will be paired to the Doorbell Text Select entity instead of the camera entity. 

As for the sensor, the best way we though to do it is to make an [Input Text helper](https://www.home-assistant.io/integrations/input_text/) and only set the text from it. You can go ahead and set up the input Text helper now and I will get the new service up for the stable 0.11 release for you to migrate to (before the core merge/0.12).

**Comment by edwardmp** [comment]
Thanks! Keep me posted
