### ISSUE TITLE
Cannot install older build (091)

### ISSUE THREAD

**Issue by garethcook** [briis/unifiprotect#433]
### Home Assistant Version?

core-2021.12.6

### UniFi Protect Version?

1.18

### UniFi Protect HA Integration version?

0.9.1

### What happened?

I'm currently using HomeKit to surface Protect via HA, I want to try to move to this method instead. I am on Protect 118 and don't intend to upgrade, nor the UDMP (108). Too many horror stories and I don't need to move.

With that, I need to install the 091 build but I'm not seeing that option in HACS, only 0.11.0 to 0.11.4. Selecting beta opens up some 12 builds

I tried looking for the manual process bypassing HACS, but I couldn't find that neither. Is there a secret function to open up historical build installation via HACS?

Thanks

**Comment by briis** [comment]
HACS per default only shows the last 5 releases, and including betas there have been many releases since 0.9.1.
If you go to the Integrations page and find the HACS integration, you can click on Configure and define the number of releases you want to show. You need to have anywhere between 15 and 25 releases depending on if you clicked *Show Beta Versions*

After you done this, it will take a little time for HACS to populate all the new releases, so have a little patience.

**Comment by AngellusMortis** [comment]
> don't intend to upgrade, nor the UDMP (108)

I really hope you are not running UniFi Network on that UDM Pro: https://logging.apache.org/log4j/2.x/security.html

**Comment by garethcook** [comment]
> > don't intend to upgrade, nor the UDMP (108)
> 
> I really hope you are not running UniFi Network on that UDM Pro unpatched: https://logging.apache.org/log4j/2.x/security.html
> 
> And yes, it affects UniFi: https://community.ui.com/releases/Security-Advisory-Bulletin-023-023/808a1db0-5f8e-4b91-9097-9822f3f90207

I am, but all cloud access is off

**Comment by AngellusMortis** [comment]
> I am, but all cloud access is off

That does not matter. The UDM Pro acts like a gateway to the Internet. Even if you have it firewalled, traffic is still coming in and being logged. The vulnerability is in the _logging_. If your UDM is compromised, next they can get your DNS without any issues, and you will be in a world of trouble since UniFi Network controls DNS for DHCP.

**Comment by AngellusMortis** [comment]
Going to close out this issue and pin it for anyone in the future that needs to figure out how to get the pre-0.10 versions.
