### ISSUE TITLE
sensor.*_detected_object only logs on state changing to none

### ISSUE THREAD

**Issue by segfaultex** [briis/unifiprotect#453]
### Home Assistant Version?

2021.12.9

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.12.0-beta8

### What happened?

During my doorbell smart detection troubleshooting I noticed that all of my G4 cameras only log the _detected_object state when it changes to none.

Expecting it to log when it changes to "person" or "vehicle"

![image](https://user-images.githubusercontent.com/3958108/149042358-8e247dd8-5803-401b-b391-54307e77ceec.png)

**Comment by AngellusMortis** [comment]
I just tested this, and this is either expected behavior or a HA bug (not the unifiprotect integration). If an entity creates two log entries rapidly (less then 60 seconds), the previous ones are essentially hidden. It only shows the most recent one for the minute. If you take a phone with the HA app and load the log book entry, you can refresh it in real time and see the log book show "person" and then replace it with "none" when it turns off.

It may be a limitation for how the timeseries is implement for the logbook.
