### ISSUE TITLE
Feature request: Add name of smart detection zone to event

### ISSUE THREAD

**Issue by mullermn** [briis/unifiprotect#458]
### Discussed in https://github.com/briis/unifiprotect/discussions/327

In the discussion linked above about motion zone names it is mentioned that it is already feasible to extract the name of the smart detection zone which triggered an event. Can I please request that this attribute is added to the event in Home Assistant?

As example use cases, with an external camera and multiple smart detection zones I could make more complex behaviours based on whether someone is approaching or leaving a building, or where I have cameras covering multiple properties I could create a 'doorbell' notification that notifies the correct people.

**Comment by AngellusMortis** [comment]
So, looking into it more from the Home Assistant side, it is not possible to expose the data. At least I cannot think of a way with the current architecture of how attributes are constructed. Sensors cannot really "fetch" data for attributes since the update loop is not async. They have to have the data readily available to them already. The triggering zones in the smart detect track require an extra step to fetch them after the event has been detected. I cannot do this inside of the HA update loop.

The only way to add this would be to preemptively fetch the smart detect track for _every_ event, which greatly increase the traffic to the NVR and potentially slowdown how fast motion/smart detects are reported, which would be bad. 

I would really sorry because this would be cool to implement but does not really fit in with the current architecture of HA.

**Comment by mullermn** [comment]
Thanks for the response. 

Thinking outside the box a bit, is there any way that you could expose a service (or similar, I'm very beginner in HA terminology) that would enable active fetching of the data? So instead of the zone being an attribute of the primary event we could use a script or a template sensor or something that could call back to the integration to retrieve the zone in response to the smart event?

That may be gibberish. I'm trying to capitalise on being too dumb to know what can't be done!

**Comment by segfaultex** [comment]
I am very interested in this as well.
I have a different smart detection zone for my front door path vs the sidewalk and would like notifications of people only on the front door not the side walk.

**Comment by AngellusMortis** [comment]
Dug into it more, the smart detection track is not generated until the event ends. So, there is no way to get which zone triggered the event and then add it to the sensor as an attribute before the event ends.

I am going to close this one can "not possible'. Sorry guys, I tried.
