### ISSUE TITLE
Switch naming convention G4 Instant status light not consistant with the rest of the status light sensors

### ISSUE THREAD

**Issue by Calimerorulez** [briis/unifiprotect#463]
### Home Assistant Version?

2021.12.9

### UniFi Protect Version?

1.21.0-beta3

### UniFi Protect HA Integration version?

0.12-beta11

### What happened?

I just added a G4 Instant, and I noticed that the switch for the status light has a different naming convention than the switches for my other camera's:

![image](https://user-images.githubusercontent.com/1130552/149834491-52b4fd7d-a5cc-4723-9149-e41e9b76d654.png)

G4 Instant is switch.g4_instant_status_light_on
G3 Flex is switch.status_light_on_g3_flex

**Comment by AngellusMortis** [comment]
This is because those G3 Flex entities likely existed before the 0.11 update. HA does not automatically update entity IDs when they change in the code. Only the names do. Changing the entity IDs could break automations/dashboards. 

You can manually rename them if you like, or you can delete the integration entry and re-add it to get the new updated ones for all of the entities.
