### ISSUE TITLE
service set_recording_mode missing under domain unifiprotect

### ISSUE THREAD

**Issue by JurgenJess** [briis/unifiprotect#469]
### Home Assistant Version?

2021.12.10

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.12.0

### What happened?

After update to UniFi Protect HA 0.12.0 some options are broken. Node-red error "Call-service error. Service not found."

The Service unifiprotect.set_recording_mode is missing after updating. Because of this I can’t set the recording_mode of the camera entity ID.

<img width="495" alt="Schermafbeelding 2022-01-29 om 01 00 32" src="https://user-images.githubusercontent.com/75953230/151637566-cf53abe8-b0c4-4fe0-afec-0e909f3d04fb.png">

**Comment by AngellusMortis** [comment]
See 

https://github.com/briis/unifiprotect/releases/tag/v0.11.0
https://github.com/briis/unifiprotect/releases/tag/v0.12.0

**Comment by JurgenJess** [comment]
Could you please explain. Thx

**Comment by AngellusMortis** [comment]
> `unifiprotect.set_recording_mode` -- use the select introduced in 0.10 instead

The select platform the `select.select_option` service you can use.

**Comment by JurgenJess** [comment]
select.select_option doesn't work.

**Comment by AngellusMortis** [comment]
`select.select_option` does work. We tested it and it is an out of the box HA service. You will just need to adjust your Node Red flow.

I apologize for the inconvenience, but that service needed to be removed because it is duplicated by `select.select_option`. We cannot add it back because core will not allow duplicate functionality. Please make sure you read patch notes for deprecations/breaking changes before upgrading.

**Comment by AngellusMortis** [comment]
```
service: select.select_option
data:
  option: Never
target:
  entity_id: select.back_yard_camera_recording_mode
```

**Comment by JurgenJess** [comment]
Thx, that was the solution!
