### ISSUE TITLE
Garage Door Surveillance / Camera Delay

### ISSUE THREAD

**Issue by mgoetting** [briis/unifiprotect#51]
Thx for this integration of protect, awesome work! :-)

I have one issue, using one of the cameras (G3 Pro / Protect on UDM Pro) in combination with a garage door control, which is very nice as you can see whats happening in front of the garage area.

In this usecase delay of the camera becomes somewhat an issue, I have about 20 sec. (live option)compared to real, that means the garage door is opening / closing, but I can see it in the picture starting when it is already open or close in real. Does not sound much, but in this case it is already feeling strange.

The delay in the protect app is much less. I know there is different approach with RTSP beeing used compared to the app and ubiquiti is not famous for their 3rd party API support, but maybe there is a chance to optimize this somehow in the future...

**Comment by briis** [comment]
Hi @mgoetting 
You are welcome, glad it is useful.

You are touching on one of my biggest pain points. The only Live Stream supported by Unifi Protect is currently the RTSP Stream, and in combination with Home Assistant that gives a real-time delay of 10-20 seconds. From my side I cannot do anything as I just deliver the address to the Live Stream, this has to be fixed in Home Assistant by optimising the Stream component.
So currently, I cannot really do much about it. Sorry.
/B

**Comment by briis** [comment]
I will close this issue as it as generic HA issue with the stream component.
