### ISSUE TITLE
hass.data storage

### ISSUE THREAD

**Issue by bdraco** [briis/unifiprotect#63]
https://github.com/briis/unifiprotect/blob/62c90b4912e81fcf989769839c730245a813e6b7/custom_components/unifiprotect/__init__.py#L100

The current Home Assistant standard is to store data for each config entry under DOMAIN, entry_id

You could change the above to:
`hass.data.setdefault(DOMAIN, {})[entry.entry_id]`

and then update all references in the rest of the code to use the entry_id

**Comment by briis** [comment]
I have now changed this in all files so it should not comply with HA standards.. 
I still have the issue that the Server Device disappears after a restart, so that only the cameras are shown as devices. I can't figure out what I am doing wrong so that the Parent Device created in __init__ does not survive a restart.

**Comment by briis** [comment]
The code change has been implemented. Thx.
