### ISSUE TITLE
Snapshot return same image?

### ISSUE THREAD

**Issue by rajeevan** [briis/unifiprotect#88]
I'm running unify-protect and using your custom component to integrate with hassio. I Also have the HASS-Deepstack-object running to detect person in the image from camera.

I have an automation implemented that run's every 5 seconds and process the image from Camera. I notice that it's processing same image and image only get refreshed between 10-15 seconds.

After looking through `image_processing` and `HASS-Deepstack-object` (with my limited python knowledge) I did some debugging that find that if I save the image using snapshot; I get the same image for 10-15 seconds.

I read through this custom component implementation and the low-level library to see if I can make any sense; as far I see; everything seems to be good.

Do you know of any limitation on unify side for this behavior or other reason?
Does this have any impact? https://github.com/briis/pyunifiprotect/blob/master/pyunifiprotect/unifi_protect_server.py#L488

Thanks, Hope you could enlighten me on this.

**Comment by briis** [comment]
I just tested this on my system, and I can confirm I get the same result - image is not updated instantly.
This line ` time_since = int(time.mktime(datetime.datetime.now().timetuple())) * 1000` should not be the problem, as all it does is basically to take current time and converting it to a Unix Timestamp. It has a new value every second, so that can not be the cause of the problem. 
I will have to dig in to the the Unifi Protect APP to see how often it actually delivers a new image, to see if that is a limitation.

**Comment by briis** [comment]
So I did some more testing, and there might be a feature in the API, that ensures we get the latest image, but currently I did not find it.
HOWEVER, I found that if you enable Anonymous Snapshot on each camera, and call that, then the image is instantly updated. I am working on adding support for this in the Integration. Stay tuned.

**Comment by rajeevan** [comment]
You are awesome 🏅  Thanks a lot for finding this & fixing this..

**Comment by briis** [comment]
hi @rajeevan 
It is now done, but before I release this, could you test if it works, and fixes your problems? 
To to this you will need to:
* Copy all the files from https://github.com/briis/unifiprotect/tree/master/custom_components/unifiprotect and overwrite the files in your current `custom_components/unifiprotect` directory in Home Assistant. Remember the two files in the `translations` directory.
* Restart Home Assistant.

Now follow this description to enable Anonymous Snapshots:
1. Login to each of your Cameras by going to http://CAMERA_IP. The Username is *ubnt* and the Camera Password can be found in Unifi Protect under *Settings*.
2. If you have never logged in to the Camera before, it might take you through a Setup procedure - just make sure to keep it in *Unifi Video* mode, so that it is managed by Unifi Protect.
3. Once you are logged in, you will see an option on the Front page for enabling Anonymous Snapshots. Make sure this is checked, and then press the *Save Changes* button.
4. Repeat step 3 for each of your Cameras.
5. Now go to the Integrations page in Home Assistant. Find the Unifi Protect Widget and press options.
6. Select the checkbox *Use Anonymous Snapshots* and press *Submit*

Let me know how this works out for you.

**Comment by rajeevan** [comment]
@briis Thanks for the instructions; I have tested with anonymous snaps enabled and it works great.
I tested with Option enabled in HA & without enabled.
Without is still the same as before and with the option enabled; it generate new image (I tested 1 per second and works fine).

One last question: Is there a reason why the origin image was set to size `1024*576`? I have 1080p rtsp enabled and anonymous snaps return image in 1080p resolution; Quality is quite good looking too!

Thanks again for finding a solution 👍

**Comment by briis** [comment]
Fantastic, great that it works. And no, there is actually not a good reason for the image size on the Non Anonymous snapshots. If I remember I thought that they should not be too big files. But working on this, I have now changed the image sizes for the non anonymous snapshots also, so that they are 1920x1080 for most Cameras and 3840x2160 for G4 Pro Cameras (4K).

I will make a final release and post to HACS. Thanks for reporting this. Please close this issue if you are happy with the solution.

**Comment by rajeevan** [comment]
Thanks for the speedy resolution 👍  I will close this issue

**Comment by rajeevan** [comment]
@briis  I think I have the answer to how to make it refresh 😄  I saw that they have a query in url `&force=true` Which force refresh images. Without it, there is a delay when I try with unifiprotect url.
something to add > https://github.com/briis/pyunifiprotect/blob/master/pyunifiprotect/unifi_protect_server.py#L499
Hope this is what you were looking for ..

**Comment by briis** [comment]
GOOD FIND @rajeevan 
I just made a quick test, by adding force=true to the params - and it works 😂
I will release this ASAP.
THANKS

**Comment by briis** [comment]
If you want to test it for me now, go to your `custom_components/unifiprotect` directory and edit the `manifest.json` file.
Change this `pyunifiprotect==0.18.1` to this `pyunifiprotect==0.18.3` and restart Home Assistant.
If you changed the options to use Anonymous Snapshots, please make sure you deselect that again.

**Comment by rajeevan** [comment]
Yes, it works 👍
