### ISSUE TITLE
Doesn't appear on Integrations page

### ISSUE THREAD

**Issue by dcode** [briis/unifiprotect#92]
I'm brand new to Home Assistant and running the OVA on a esxi node on my network. I have a CloudKey gen2+. I tried following your instructions, but I can't any mention of "Unifi Protect" in the main integrations page or on the community page. I have a "Ubiquiti Unifi", which connects to my cloud key and lets me manage devices on my network. When I go to the [community](https://www.home-assistant.io/integrations/) page, I don't see protect listed there either.

Can you help?

**Comment by briis** [comment]
Hi Derek,
Welcome to the world of Home Assistant. It is the most comprehensive Home automation system out there, but that can also make it a bit frustrating getting up and running. Have patience, because once you got it, you don't find anything better.

To add new devices or systems to Home Assistant, you basically follow two paths:
1) The official supported Integrations, you linked to above
2) Custom Integrations, that are not currently part of the core Home Assistant

Unifi Protect is in the second category, as I have not asked to get it included in the core yet. The best way to get these kind of Integrations installed, is by first installing another Custom Integration called *Home Assistant Community Store* or HACS. Once this is installed, you can search for Integrations like Unifi Protect, and install them directly from there.

So I would recommend that you start by installing HACS and there is good documentation on how to do that here https://hacs.xyz/.
When that is done, go in to HACS and search for Unifi Protect, and HACS will install it for you. Then you need to follow the instructions in the [README.md](https://github.com/briis/unifiprotect) to get Unifi Protect up and running.

**Comment by mcaminiti** [comment]
Any milestone you are waiting on to submit it as an official component? Looks great!

**Comment by briis** [comment]
Hi Matt,
No not really, I currently have nothing extra to add. The reason I am not submitting this as an official component is, that I have no clue how to setup tests and all the other Github stuff that needs to be done, to submit it.

**Comment by briis** [comment]
Closing this issue as it seems to be closed.
