### ISSUE TITLE
Can't find anywhere to add Unifi-protect server config after HACS install in HA 0.114.0

### ISSUE THREAD

**Issue by mcondren** [briis/unifiprotect#98]
Hello,

I just updated to the latest version of HA (0.114.0).  I did read the readme.  I went to HACS and installed the unifi protect integration. I rebooted and it shows in HACS as installed.  I also see it in 'custom_components'.  However, I don't understand the paragraph in the readme for adding a cloud Key +.  There is no protect in the regular integrations page and the HACS addon does not give a place to add ip, login, etc.  I must be missing something easy...

**Comment by zeit0dn1** [comment]
I have the same issue in 0.113.1, and after upgrading to 0.114.0.  There isn't anywhere to add login config.

**Comment by briis** [comment]
This is almost always caused by a caching issue on your browser, so do the following:

Click the *Settings* Tab on the left, and then select *Integrations*. Once you are on this page, do a Hard Refresh of your Browser, then click the + Button in the lower right corner, and you should be able to find Unifi Protect on the list. Click that, and you can then enter your information.

Let me know if this works.

**Comment by mcondren** [comment]
Yup, that did it.  Thanks.
